name: EdgeXFoundry-Snap
on:
  schedule:
  - cron:  "0 6 * * *"
jobs:
  build-snap:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: canonical/edgex-cli
        fetch-depth: 0
        ref: ireland-lp
    - name: Build the snap
      uses: snapcore/action-build@v1
    - name: Uploading snap artifact
      uses: actions/upload-artifact@v2
      with:
        name: snap-files
        path: "*.snap"
    - name: MM Failure
      if: ${{ failure() }}
      run: |
        curl -i -X POST -H 'Content-Type: application/json' -d '{"username" : "github-builds", "text" : "<!channel> :warning: Build failed [${{github.event_name}}] ${{github.workflow}} [See logs](https://github.com/canonical/edgex-sync/actions/runs/${{github.run_id}}) "}' ${{secrets.MATTERMOST}}
  test-snap:
    runs-on: ubuntu-latest
    needs: build-snap
    steps:
    - name: testing snap install
      uses: actions/download-artifact@v2
      with:
        name:  snap-files
    - shell: bash
      run: |
        sudo snap install --dangerous *.snap
    - name: MM Failure
      if: ${{ failure() }}
      run: |
        curl -i -X POST -H 'Content-Type: application/json' -d '{"username" : "github-builds", "text" : "<!channel> :warning: Test failed [${{github.event_name}}] ${{github.workflow}} [See logs](https://github.com/canonical/edgex-sync/actions/runs/${{github.run_id}}) "}' ${{secrets.MATTERMOST}}
  build-launchpad:
    runs-on: ubuntu-latest
    needs: test-snap
    steps:
      - name: Kick off Launchpad build
        uses: canonical/edgex-launchpad-build-action@v1.4
        with:
          edgex_snap: "edgex-cli"
          consumer_name: ${{ secrets.LP_CONSUMER_NAME }}
          access_token: ${{ secrets.LP_ACCESS_TOKEN }}
          access_secret: ${{ secrets.LP_ACCESS_SECRET }}
      - name: MM Failure
        if: ${{ failure() }}
        run: |
          curl -i -X POST -H 'Content-Type: application/json' -d '{"username" : "github-builds", "text" : "<!channel> :warning: Launchpad build failed [${{github.event_name}}] ${{github.workflow}} [See logs](https://github.com/canonical/edgex-sync/actions/runs/${{github.run_id}}) "}' ${{secrets.MATTERMOST}}

